### ISSUE TITLE
App is not running , giving error

### ISSUE THREAD

**Issue by laxman-ram-iconnect** [chaimPaneth/react-native-zoom-bridge#1]
i trying for android.
"react-native": "0.62.2",

after npm I and placing the lib in node_module

getting below error when running npx react-native run-android

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
152 actionable tasks: 2 executed, 150 up-to-date
/home/turbo/devel/doconvid/node_modules/react-native-zoom-bridge/android/src/main/java/com/appgoalz/reactnative/RNZoomBridgeModule.java:26: error: RNZoomBridgeModule is not abstract and does not override abstract method onZoomAuthIdentityExpired() in ZoomSDKInitializeListener
public class RNZoomBridgeModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, MeetingServiceListener, LifecycleEventListener {
       ^
Note: /home/turbo/devel/doconvid/node_modules/react-native-zoom-bridge/android/src/main/java/com/appgoalz/reactnative/RNZoomBridgeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-zoom-bridge:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

my build.gradle file

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        flatDir {
            dirs "$rootDir/../node_modules/react-native-zoom-bridge/android/libs"
        }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven {url "https://maven.google.com"}
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by laxman-ram-iconnect** [comment]
issue was relalated to zoom sdk version and react-native compile sdk.
i was able get the compatible zoom sdk and replace the compliesdk and it worked.
Thank You very much

**Comment by rananajam1** [comment]
@laxman-ram-iconnect how did you get the compatible zoom sdk and what did you replace for the compilesdk
