### ISSUE TITLE
Changes in node_modules folder

### ISSUE THREAD

**Issue by KawaljeetSBagga** [chaimPaneth/react-native-zoom-bridge#10]
Hi, Thank you for the awesome package. I believe that we should not make changes in the node_modules folder for fixing bugs as you have suggested in RNZoomBridge.h file for import statements and also we have removed <MobileRTC.h/> from imports, but I think ideally this should not be the case. Is there a way or fix that may be you can apply and then publish it?

**Comment by chaimPaneth** [comment]
The Zoom SDK comes with the import headers that are made for imbedding the SDK as a framework to the main project and not in the pods but we make use of the SDK in a pods project.

I can create something automatic for header renaming to make it work in a pod project but then ZOOM might change their SDK and this will be obsolete so I'm not sure if it's worth spending time on this.

Any ideas on this would be appreciated of course.

**Comment by loria33** [comment]
Hey , needed this urgently for a project so created this 
This is the dev install 
rm -f -r ./node_modules/react-native-zoom-meetings/ios/libs && \
mkdir -p ./node_modules/react-native-zoom-meetings/ios/libs && \
cd ./node_modules/react-native-zoom-meetings/ios/libs && \
curl -L https://github.com/zoom/zoom-sdk-ios/releases/download/v4.6.15084.0206/ios-mobilertc-all-4.6.15084.0206-n.zip > file.zip && \
unzip file.zip && \
cd lib && \
mv * ../ && \
cd ../ && \
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTC.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+AppShare.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Audio.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Chat.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Customize.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+inMeeting.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+User.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Video.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+VirtualBackground.h
sed -i.bak 's/#import <MobileRTC\//#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Webinar.h
rm file.zip && \
rm -r lib && \
rm -r MobileRTCSample

**Comment by chaimPaneth** [comment]
I've implemented the auto renaming of the imports in latest version, closing this issue.
