### ISSUE TITLE
Android Zoom SDK update

### ISSUE THREAD

**Issue by user1701** [chaimPaneth/react-native-zoom-bridge#17]
Zoom Android SDK was updated yesterday and would be great if you update the package to the latest changes...
`/node_modules/react-native-zoom-bridge/android/src/main/java/com/appgoalz/reactnative/RNZoomBridgeModule.java:113: error: cannot find symbol
      params.zoomToken = zoomToken;
            ^
  symbol:   variable zoomToken
  location: variable params of type StartMeetingParamsWithoutLogin`

**Comment by ankitchaudhary** [comment]
I am also facing the same issue last 2 days
RNZoomUsBridgeModule.java:128: error: cannot find symbol
        params.zoomToken = zoomToken;
              ^
  symbol:   variable zoomToken
  location: variable params of type StartMeetingParamsWithoutLogin

**Comment by longhomit** [comment]
I try remove 'params.zoomToken = zoomToken;' and it soveled

**Comment by user1701** [comment]
I have updated import_aars.sh with patch-package 
`curl -L https://github.com/zoom/zoom-sdk-android/archive/v4.6.21666.0429.zip > file.zip &&`

**Comment by user1701** [comment]
> I try remove 'params.zoomToken = zoomToken;' and it soveled

I can't do this, an app is building on a CI and after clear installation, the build will be failed.

**Comment by longhomit** [comment]
Another way is download older version of zoom us sdk.

**Comment by ankitchaudhary** [comment]
Any update on this issue?

**Comment by chaimPaneth** [comment]
Iv'e pushed a fix to the library version 1.0.17 and changed the SDK import bash files to download previous working version v4.6.21666.0428

Try version v4.6.21666.0428, download it from here

ios-dev: https://github.com/zoom/zoom-sdk-ios/archive/v4.6.21666.0428.zip
ios-prod: https://github.com/zoom/zoom-sdk-ios/archive/v4.6.21666.0428.zip
android: https://github.com/zoom/zoom-sdk-android/archive/v4.6.21666.0429.zip

put them in node_modules/react-native-zoom-bridge/ios/libs && node_modules/react-native-zoom-bridge/android/libs
then run pod install then rename the headers for ios.

Tell me if it worked.

I will update the library to work with the latest SDK when I get the chance.

**Comment by user1701** [comment]
@chaimPaneth I have 2 errors on ios "Duplicate interface definition for class 'MobileRTC'" and "Property has a previous declaration", any ideas?

**Comment by chaimPaneth** [comment]
@user1701 This usually means that after importing the SDK you didn't rerun `pod install` and only then rename the headers.

1: Import (prod or dev) SDK using bash file
2: Run pod install
3: Open xcode and find & replace "MobileRTC/" with ""
4: Rerun

**Comment by user1701** [comment]
@chaimPaneth thanks, it helped me, I have to make builds on CI, how I can automate it?

**Comment by user1701** [comment]
@chaimPaneth I have added code from the [answer](https://github.com/chaimPaneth/react-native-zoom-bridge/issues/10#issuecomment-629743389) at the end of import scripts and a bit updated because I have an issue with special characters... and now it works well

```
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTC.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+AppShare.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Audio.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Chat.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Customize.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+inMeeting.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+User.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Video.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+VirtualBackground.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+Webinar.h
sed -i.bak 's/\#import <MobileRTC\//\#import </g' ./MobileRTC.framework/Headers/MobileRTCMeetingService+BO.h
```

**Comment by chaimPaneth** [comment]
@user1701 I've implemented the auto renaming of the imports in latest version, closing this issue.
