### ISSUE TITLE
Error in building archive iOS

### ISSUE THREAD

**Issue by deepak-jha-kgp** [chaimPaneth/react-native-zoom-bridge#18]
I'm trying to build an archive to put my app in the App Store. But getting following errors. Would appreciate if you could look into them. 
SDK type:  Release
Errors: 
1: `No visible @interface for 'MobileRTC'  the selector 'setMobileRTCDomain:'`
2: `Property 'userToken' not found on object of type 'MobileRTCMeetingStartParam4WithoutLoginUser *'; did you mean 'userType'?`

Both the errors have origin in **RNZoomBridge.m**
Really appreciate what you've build and have been using this in android for quite some time now. It would be great if you could help me deal with this iOS situation as well.

**Comment by chaimPaneth** [comment]
Hi @deepak-jha-kgp seems that the new zoom SDK broke the lib I'm gonna update this in the coming days in the meantime try to download the previous SDK version and use that instead of the latest.

Thanks

**Comment by chaimPaneth** [comment]
Iv'e pushed a fix to the library version 1.0.17 and changed the SDK import bash files to download previous working version v4.6.21666.0428.

I will update the library to work with the latest SDK as soon as I get the chance.
