### ISSUE TITLE
App installation Fail in IOS device after linking the package

### ISSUE THREAD

**Issue by Palwisha77** [chaimPaneth/react-native-zoom-bridge#19]
after installing the package and follow all the steps guided in the installation part and fix ed the headers errors, the build created successfully, but it won't install on the device. It would fail saying "Unable to install application". "Failure reason: No code signature found". Please guide me if I missed something.  Need urgent help.

**Comment by chaimPaneth** [comment]
Hi @Palwisha77 this error means that you don't have sufficient code signing for the app to install to a real device, you need to use your apple developer account to get the correct signing but this issue doesn't have to do with this library so I'm closing this.

Thanks

**Comment by aditiproctur** [comment]
@Palwisha77 Did you solve this error? Please share the Answer. I need urgent help. I am facing the same issue after installing this package. I am trying to solve this issue past 2 days. 
Thank you in advance.

**Comment by socheat-leang** [comment]
@chaimPaneth . I think this is an issue. Many people face this issue include me. To install in simulator, it works as expected. but it won't work physical device. 

It's not about apple developer account signing.
