### ISSUE TITLE
Error on react-native run-android

### ISSUE THREAD

**Issue by rananajam1** [chaimPaneth/react-native-zoom-bridge#2]
Heres the log:

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find us.zoom.sdk:commonlib:.
     Searched in the following locations:
       - file:/E:/ZoomApp/node_modules/react-native-zoom-bridge/android/libs/commonlib.aar
     Required by:
         project :app > project :react-native-zoom-bridge
   > Could not find us.zoom.sdk:mobilertc:.
     Searched in the following locations:
       - file:/E:/ZoomApp/node_modules/react-native-zoom-bridge/android/libs/mobilertc.aar
     Required by:
         project :app > project :react-native-zoom-bridge

**Comment by laxman-ram-iconnect** [comment]
first you will need to download the zoom SDK for android and place it in under /node_modules/react-native-zoom-bridge/android/libs.
Download the SDK from official page(but keep it in mind before downloading check the compatibility with your react-native androidapi version- which u can find in readme section)

get it from here https://github.com/zoom/zoom-sdk-android/releases

find the correct release as per the android API

**Comment by chaimPaneth** [comment]
Hi @rananajam1 

@laxman-ram-iconnect is correct the compiler is saying that your missing the aar files in libs folder so you need to fix the setup process check out the readme https://github.com/chaimPaneth/react-native-zoom-bridge#android I've created a script file that could import the SDK automatically for your convenience.

Thanks
