### ISSUE TITLE
Error On run-android

### ISSUE THREAD

**Issue by deepak-jha-kgp** [chaimPaneth/react-native-zoom-bridge#3]
React Native Version: 0.62.2
Platform : Android
Zoom SDK version -v4.6.21666.0429
Tried with 2 different gradle build settings, got the same error
Setting 1:
       `buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29`

Setting 2: 
       `buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28` 

When? :  While trying to build and run on android using react-native run-android

Error log 

> `......\node_modules\react-native-zoom-bridge\android\src\main\java\com\appgoalz\reactnative\RNZoomBridgeModule.java:26: error: RNZoomBridgeModule is not abstract and does not override abstract method onZoomAuthIdentityExpired() in ZoomSDKInitializeListener
> public class RNZoomBridgeModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, MeetingServiceListener, LifecycleEventListener {
>        ^
> Note: ......\node_modules\react-native-zoom-bridge\android\src\main\java\com\appgoalz\reactnative\RNZoomBridgeModule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-zoom-bridge:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.`

**Comment by prateekagarwal721** [comment]
Facing the same issue +1

**Comment by chaimPaneth** [comment]
Hi @deepak-jha-kgp 

I will check this out, for now can you try with the previous SDK https://github.com/zoom/zoom-sdk-android/releases/tag/v4.6.15801.0403 might be the latest SDK had some breaking change

Thanks

**Comment by laxman-ram-iconnect** [comment]
https://github.com/zoom/zoom-sdk-android/tree/v4.6.21666.0429

as per the doc u should have the lastest API please read readme correctly,

this might be the issue

Android Project:
Support AndroidX
Gradle settings:
compileSdkVersion: 29+
buildToolsVersion: 29+
minSdkVersion: 21
Required dependencies
implementation 'androidx.multidex:multidex:2.0.0'
implementation 'androidx.recyclerview:recyclerview:1.0.0'
implementation 'androidx.appcompat:appcompat:1.0.0'
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
implementation 'com.google.android.material:material:1.0.0-rc01'

**Comment by deepak-jha-kgp** [comment]
> the

**Comment by deepak-jha-kgp** [comment]
Sure @chaimPaneth , will try that. Thanks

**Comment by deepak-jha-kgp** [comment]
Hey @laxman-ram-iconnect  please see settings 1 in the issue detail 
`buildToolsVersion = "29.0.2" minSdkVersion = 21 compileSdkVersion = 29 targetSdkVersion = 29`
I guess I'm already taking care of the requirements. Thanks

**Comment by prateekagarwal721** [comment]
@deepak-jha-kgp 
 @Override
  public void onZoomAuthIdentityExpired() {
     Log.d(TAG,"onZoomAuthIdentityExpired:");
    }
override the method

**Comment by deepak-jha-kgp** [comment]
Hey @prateekagarwal721 where is this method declared? Couldn't find it in RNZoomBridgeModule.java RNZoonBridgePackage.java

**Comment by prateekagarwal721** [comment]
@deepak-jha-kgp it is not declared other method of zoomsdklistener is declared add this too in 
RNZoomBridgeModule.java

**Comment by prateekagarwal721** [comment]
@chaimPaneth there is typo error
import com.appgolaz.reactnative.RNZoomBridgePackage
should be import com.appgoalz.reactnative.RNZoomBridgePackage

**Comment by chaimPaneth** [comment]
@prateekagarwal721 are you using the latest version? This typo was from a previous version.

**Comment by prateekagarwal721** [comment]
@chaimPaneth using "1.0.13"

**Comment by deepak-jha-kgp** [comment]
The typo was in the readme I guess. Thanks @prateekagarwal721  adding the method solved my problem. But now getting a different weird error.

> * What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\hp\.gradle\caches\transforms-2\files-2.1\17b28cead0b13c2ce169fc096a0d701d\jetified-mobilertc\AndroidManifest.xml:129:9-133:51: AAPT: error: attribute android:foregroundServiceType not found.

**Comment by prateekagarwal721** [comment]
@deepak-jha-kgp i also faced same issue add
implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0-rc01'

**Comment by deepak-jha-kgp** [comment]
It didn't help @prateekagarwal721 :(

**Comment by chaimPaneth** [comment]
@prateekagarwal721 

I have updated the library t0 1.0.14 with the necessary override method.
Can you try to start from a fresh install as it seems that you have something is cached from a previous version

Try 
`npm uninstall react-native-zoom-bridge` 
`npm i --save react-native-zoom-bridge` 

For iOS:
`chmod +x ./node_modules/react-native-zoom-bridge/bin/import_dev_sdk.sh`
`./node_modules/react-native-zoom-bridge/bin/import_dev_sdk.sh`
`cd ios`
`pod install`
Afterwards you will have to rename the headers imports removing `MobileRTC/` from the imports.

For Android:
`chmod +x ./node_modules/react-native-zoom-bridge/bin/import_aars.sh`
`./node_modules/react-native-zoom-bridge/bin/import_aars.sh`
then open the project in Android Studio, clean the project and invalidate cache and retry to build.

Thanks

**Comment by prateekagarwal721** [comment]
@deepak-jha-kgp  are ypu using targetsdk version i.e 29?

**Comment by prateekagarwal721** [comment]
@chaimPaneth if zoom apk is not installed in device then its throwing error code 99, what can be done for that?

**Comment by chaimPaneth** [comment]
@prateekagarwal721 Iv'e just updated the library again :-) to version 1.0.15 with updated dependencies for latest SDK and I've updated the readme as well.

Thanks

**Comment by deepak-jha-kgp** [comment]
Thank you guys, everything is perfect now. 
Just a random question, the aar file is of around 90mbs, which increases the apk size by a lot. Is there any way we can deliver that to users' devices after the app being installed?

**Comment by chaimPaneth** [comment]
@deepak-jha-kgp 

Great to hear you succeeded, I'm closing this issue now as the latest question is off topic; if you can kindly open a new issue regarding your inquiry that would be appreciated.

Thanks
