### ISSUE TITLE
Duplicate interface definition for class 'MobileRTCSDKInitContext' when trying to build ios

### ISSUE THREAD

**Issue by prateekagarwal721** [chaimPaneth/react-native-zoom-bridge#5]

**Comment by prateekagarwal721** [comment]
Showing Error
Duplicate interface definition for class 'MobileRTCSDKInitContext' 
Property has a previous declaration
in MobileRTC.h while building ios

**Comment by chaimPaneth** [comment]
Try to remove all "MobileRTC/" from the header imports and retry, what I do is search MobileRTC/ in project and replace with "" and rebuild.

Tell me if it worked.

**Comment by loria33** [comment]
Hey Yes it worked , replaced all MobileRTC/ with nothing , and IOS now compiles.

**Comment by chaimPaneth** [comment]
@loria33 great! I've updated the readme to make this more clear in the setup process.

**Comment by prateekagarwal721** [comment]
@Ioria33 Do you have react-native-fast-image in your project?

**Comment by loria33** [comment]
Yes

**Comment by prateekagarwal721** [comment]
@loria33 did you got fast image linking error while building ios? if yes how did you fixed?
