### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by prateekagarwal721** [chaimPaneth/react-native-zoom-bridge#9]
libsqlite3.tbd is not an object file (not allowed in a library)
libz.1.2.5.tbd is not an object file (not allowed in a library)
libc++.tbd is not an object file (not allowed in a library)

I am getting this error while building ios

**Comment by chaimPaneth** [comment]
Hi @prateekagarwal721 

Are you manually linking this library or are you using auto link with pod install?

**Comment by prateekagarwal721** [comment]
Manually Linking but now i am getting duplicate symbols for architecture x86_64 error
